export const popularHeroNames = new Set([
  "Batman",
  "Superman",
  "Wonder Woman",
  "Flash",
  "Green Lantern",
  "Aquaman",
  "Cyborg",
  "Robin",
  "Nightwing",
  "Batgirl",
  "Catwoman",
  "Harley Quinn",
  "Joker",
  "Lex Luthor",
  "Supergirl",
  "Green Arrow",
  "Black Canary",
  "Martian Manhunter",
  "Shazam",
  "Constantine",
  "Raven",
  "Starfire",
  "Beast Boy",
  "Blue Beetle",
  "Hawkman",
  "Hawkgirl",
  "Zatanna",
  "Poison Ivy",
  "Bane",
  "Deathstroke",
  "Ra's Al Ghul",
  "Darkseid",
  "Doomsday",
  "Brainiac",
  "Penguin",
  "Riddler",
  "Two-Face",
  "Scarecrow",
  "Red Hood",
  "Red Robin",
  "Doctor Fate",
  "Black Adam",
  "Mera",
  "Booster Gold",
  "Static",
  "Spider-Man",
  "Iron Man",
  "Captain America",
  "Thor",
  "Hulk",
  "Black Widow",
  "Hawkeye",
  "Wolverine",
  "Cyclops",
  "Jean Grey",
  "Storm",
  "Rogue",
  "Gambit",
  "Iceman",
  "Beast",
  "Nightcrawler",
  "Professor X",
  "Magneto",
  "Mystique",
  "Deadpool",
  "Punisher",
  "Daredevil",
  "Elektra",
  "Blade",
  "Ghost Rider",
  "Doctor Strange",
  "Scarlet Witch",
  "Vision",
  "Falcon",
  "Winter Soldier",
  "Black Panther",
  "Captain Marvel",
  "Ant-Man",
  "Wasp",
  "She-Hulk",
  "Moon Knight",
  "Nova",
  "Silver Surfer",
  "Thanos",
  "Loki",
  "Venom",
  "Carnage",
  "Green Goblin",
  "Doctor Octopus",
  "Kingpin",
  "Ultron",
  "Apocalypse",
  "Cable",
  "Domino",
  "Colossus",
  "Psylocke",
  "Kitty Pryde",
  "Emma Frost",
  "Luke Cage",
  "Iron Fist",
  "Jessica Jones",
  "Nick Fury",
  "War Machine",
  "Shang-Chi",
  "Ms Marvel",
  "Sentry",
  "Namor",
  "Black Bolt",
  "Medusa",
  "Thing",
  "Human Torch",
  "Invisible Woman",
  "Mr Fantastic",
  "Doctor Doom",
  "Galactus",
  "Rocket Raccoon",
  "Groot",
  "Star-Lord",
  "Gamora",
  "Drax the Destroyer",
  "Nebula",
  "Mantis",
  "Adam Warlock",
  "Quicksilver",
  "Archangel",
  "X-23",
  "Bishop",
  "Howard the Duck",
  "Red Skull",
  "Sabretooth",
  "Bullseye",
  "Agent Venom",
  "Superboy",
  "Kid Flash",
  "Batwoman",
  "Huntress",
  "Plastic Man",
  "Swamp Thing",
  "Deadshot",
  "Sinestro",
  "Lobo",
  "Animal Man",
  "Vixen",
  "Aqualad"
]);
